package main

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

const testRC = `# Generated by Home Manager.

IMAPAccount gmail
CertificateFile /etc/ssl/certs/ca-certificates.crt
Host imap.gmail.com
PassCmd "rbw get https://imap.gmail.com me@gmail.com"
TLSType IMAPS
User me@gmail.com

IMAPStore gmail-remote
Account gmail

MaildirStore gmail-local
Inbox /mail/gmail/Inbox
Path /mail/gmail/
SubFolders Legacy

Channel gmail
Create Both
Far :gmail-remote:
Near :gmail-local:
Patterns * ![GMail]* "[Google Mail]/Papierkorb"
SyncState *

IMAPStore inline-remote
Host imap.example.org
User bob
Pass secret
SSLType STARTTLS
Path Mail/

MaildirStore inline-local
Path /mail/inline/
Inbox /mail/inline/INBOX
SubFolders Verbatim

Channel inline
Far :inline-remote:
Near :inline-local:
`

func parseTest(t *testing.T) []*Channel {
	t.Helper()
	p := filepath.Join(t.TempDir(), "isyncrc")
	if err := os.WriteFile(p, []byte(testRC), 0o600); err != nil {
		t.Fatal(err)
	}
	chs, err := ParseMbsyncrc(p)
	if err != nil {
		t.Fatal(err)
	}
	if len(chs) != 2 {
		t.Fatalf("got %d channels", len(chs))
	}
	return chs
}

func TestParseMbsyncrc(t *testing.T) {
	chs := parseTest(t)
	g := chs[0]
	if g.Name != "gmail" || g.Account.Host != "imap.gmail.com" || g.Account.User != "me@gmail.com" ||
		g.Account.PassCmd != "rbw get https://imap.gmail.com me@gmail.com" || g.Account.Addr() != "imap.gmail.com:993" {
		t.Errorf("gmail account: %+v", g.Account)
	}
	if want := []string{"*", "![GMail]*", "[Google Mail]/Papierkorb"}; !reflect.DeepEqual(g.Patterns, want) {
		t.Errorf("patterns = %q", g.Patterns)
	}
	if g.Maildir.Path != "/mail/gmail/" || g.Maildir.Inbox != "/mail/gmail/Inbox" || g.Maildir.SubFolders != "Legacy" {
		t.Errorf("maildir: %+v", g.Maildir)
	}

	in := chs[1]
	if in.Account.Host != "imap.example.org" || in.Account.Pass != "secret" || in.Account.Addr() != "imap.example.org:143" {
		t.Errorf("inline account: %+v", in.Account)
	}
	if in.FarPath != "Mail/" || !reflect.DeepEqual(in.Patterns, []string{"INBOX"}) {
		t.Errorf("inline far path %q patterns %q", in.FarPath, in.Patterns)
	}
}

func TestFarToBox(t *testing.T) {
	g := parseTest(t)[0]
	tests := []struct {
		name  string
		delim rune
		box   string
		ok    bool
	}{
		{"INBOX", '/', "INBOX", true},
		{"inbox", '/', "INBOX", true},
		{"Sent", '/', "Sent", true},
		{"[Google Mail]/Spam", '/', "[Google Mail]/Spam", true},
		{"[GMail]/Spam", '/', "[GMail]/Spam", false},
		{"Work.Projects", '.', "Work/Projects", true},
	}
	for _, tt := range tests {
		box, ok := g.FarToBox(tt.name, tt.delim)
		if box != tt.box || ok != tt.ok {
			t.Errorf("FarToBox(%q) = %q, %v; want %q, %v", tt.name, box, ok, tt.box, tt.ok)
		}
	}

	in := parseTest(t)[1]
	if box, ok := in.FarToBox("Mail/INBOX", '/'); box != "INBOX" || !ok {
		t.Errorf("prefixed INBOX = %q, %v", box, ok)
	}
	if _, ok := in.FarToBox("Other/INBOX", '/'); ok {
		t.Error("mailbox outside prefix matched")
	}
}

func TestMatchPatterns(t *testing.T) {
	tests := []struct {
		patterns []string
		box      string
		want     bool
	}{
		{[]string{"*"}, "a/b/c", true},
		{[]string{"%"}, "a/b", false},
		{[]string{"%"}, "a", true},
		{[]string{"%", "!Trash"}, "Trash", false},
		{[]string{"*", "!Arch*", "Archive/2024"}, "Archive/2024", true},
		{[]string{"*", "!Arch*", "Archive/2024"}, "Archive/2023", false},
		{[]string{"Sent*"}, "Sent Messages", true},
		{[]string{"INBOX", "Saved"}, "Drafts", false},
	}
	for _, tt := range tests {
		if got := MatchPatterns(tt.patterns, tt.box); got != tt.want {
			t.Errorf("MatchPatterns(%q, %q) = %v", tt.patterns, tt.box, got)
		}
	}
}

func TestDirToBox(t *testing.T) {
	legacy := &MaildirStore{Path: "/m/", Inbox: "/m/Inbox", SubFolders: "Legacy"}
	verbatim := &MaildirStore{Path: "/v", Inbox: "/v/INBOX", SubFolders: "Verbatim"}
	flat := &MaildirStore{Path: "/f", Inbox: "/f/INBOX", Flatten: "."}
	tests := []struct {
		store *MaildirStore
		dir   string
		box   string
		ok    bool
	}{
		{legacy, "/m/Inbox", "INBOX", true},
		{legacy, "/m/Inbox/.sub", "INBOX/sub", true},
		{legacy, "/m/ebay", "ebay", true},
		{legacy, "/m/[Google Mail]/.Spam", "[Google Mail]/Spam", true},
		{legacy, "/m/a/.b/.c", "a/b/c", true},
		{legacy, "/elsewhere/x", "", false},
		{verbatim, "/v/a/b", "a/b", true},
		{verbatim, "/v/INBOX/x", "INBOX/x", true},
		{flat, "/f/a.b", "a/b", true},
	}
	for _, tt := range tests {
		box, ok := tt.store.DirToBox(tt.dir)
		if box != tt.box || ok != tt.ok {
			t.Errorf("DirToBox(%q) = %q, %v; want %q, %v", tt.dir, box, ok, tt.box, tt.ok)
		}
	}
}

func TestOpFlags(t *testing.T) {
	tests := []struct {
		op   Op
		want []string
	}{
		{OpPullNew, []string{"--pull-new"}},
		{OpPullNew | OpPull, []string{"--pull"}},
		{OpPush, []string{"--push"}},
		{OpPush | OpPullNew, nil},
		{OpFull, nil},
	}
	for _, tt := range tests {
		if got := tt.op.mbsyncFlags(); !reflect.DeepEqual(got, tt.want) {
			t.Errorf("%v.mbsyncFlags() = %q, want %q", tt.op, got, tt.want)
		}
	}
}

func TestBoxStateDiff(t *testing.T) {
	old := boxState{UIDValidity: 1, UIDNext: 10, Messages: 5, ModSeq: 100}
	tests := []struct {
		cur  boxState
		want Op
	}{
		{old, 0},
		{boxState{1, 12, 7, 0, 102}, OpPullNew},
		{boxState{1, 11, 5, 0, 102}, OpPull}, // new + expunge
		{boxState{1, 10, 5, 0, 101}, OpPull}, // flag change
		{boxState{1, 10, 5, 1, 100}, OpPull}, // marked unread (no modseq)
		{boxState{1, 10, 4, 0, 101}, OpPull}, // expunge
		{boxState{2, 12, 7, 0, 102}, OpPull}, // uidvalidity change
	}
	for _, tt := range tests {
		if got := old.diff(tt.cur); got != tt.want {
			t.Errorf("diff(%+v) = %v, want %v", tt.cur, got, tt.want)
		}
	}
}
